# -*- coding: utf-8 -*-
"""mineria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qeG8CpHa386wRVlAmDZMknvLF7IW-Hel
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile streamlit_app.py
# import pandas as pd
# import streamlit as st
# import matplotlib.pyplot as plt
# 
# # Configuración general
# st.set_page_config(page_title="Dashboard Universitario", layout="wide")
# st.title("📊 Dashboard de Retención y Satisfacción Estudiantil")
# 
# # Cargar datos desde el archivo CSV
# df = pd.read_csv('/content/university_student_data.csv')
# 
# # Renombrar columnas a español para que coincidan con el resto del código
# df = df.rename(columns={
#     "Year": "Año",
#     "Department": "Departamento",
#     "Term": "Periodo",
#     "RetentionRate": "Tasa de retencion",
#     "SatisfactionScore": "Puntaje de satisfacción"
# })
# 
# # 🎛️ Filtros interactivos
# st.sidebar.header("Filtros")
# year = st.sidebar.multiselect("Selecciona Año(s)", sorted(df["Año"].unique()), default=df["Año"].unique())
# department = st.sidebar.multiselect("Selecciona Departamento(s)", df["Departamento"].unique(), default=df["Departamento"].unique())
# term = st.sidebar.multiselect("Selecciona Periodo(s)", df["Periodo"].unique(), default=df["Periodo"].unique())
# 
# # Aplicar filtros
# df_filtered = df[(df["Año"].isin(year)) & (df["Departamento"].isin(department)) & (df["Periodo"].isin(term))]
# 
# # 📈 KPIs
# avg_retention = df_filtered["Tasa de retencion"].mean() * 100
# avg_satisfaction = df_filtered["Puntaje de satisfacción"].mean()
# max_retention = df_filtered["Tasa de retencion"].max() * 100
# 
# col1, col2, col3 = st.columns(3)
# col1.metric("Tasa promedio de retención", f"{avg_retention:.1f}%")
# col2.metric("Puntaje promedio de satisfacción", f"{avg_satisfaction:.2f}/5")
# col3.metric("Máxima tasa de retención", f"{max_retention:.1f}%")
# 
# st.markdown("---")
# 
# # 📊 Visualización 1: Tendencia de Retención por Año
# st.subheader("📈 Tendencia de Tasa de Retención por Año")
# fig1, ax1 = plt.subplots(figsize=(8, 4))
# for dept in df_filtered["Departamento"].unique():
#     df_dept = df_filtered[df_filtered["Departamento"] == dept]
#     ax1.plot(df_dept["Año"], df_dept["Tasa de retencion"] * 100, marker="o", label=dept)
# ax1.set_title("Tasa de Retención por Departamento y Año")
# ax1.set_xlabel("Año")
# ax1.set_ylabel("Retención (%)")
# ax1.legend()
# ax1.grid(True)
# st.pyplot(fig1)
# 
# # Visualización 2: Comparación de Satisfacción por Departamento
# st.subheader(" Comparación de Satisfacción Estudiantil por Departamento")
# fig2, ax2 = plt.subplots(figsize=(8, 4))
# df_grouped = df_filtered.groupby("Departamento")["Puntaje de satisfacción"].mean().sort_values()
# ax2.barh(df_grouped.index, df_grouped.values, color="#69b3a2")
# ax2.set_xlabel("Satisfacción Promedio (1–5)")
# ax2.set_ylabel("Departamento")
# ax2.set_title("Satisfacción Estudiantil Promedio por Departamento")
# st.pyplot(fig2)
# 
# # Visualización 3: Distribución por Periodo (Spring/Fall)
# st.subheader(" Distribución de Registros por Periodo Académico")
# fig3, ax3 = plt.subplots(figsize=(5, 5))
# term_counts = df_filtered["Periodo"].value_counts()
# ax3.pie(term_counts, labels=term_counts.index, autopct="%1.1f%%", startangle=90, colors=["#4169E1", "#FFA500"])
# ax3.set_title("Proporción de Estudiantes por Periodo")
# st.pyplot(fig3)
# 
# # Datos en pestañas
# tab1, tab2 = st.tabs(["📄 Datos filtrados", "📚 Datos completos"])
# with tab1:
#     st.dataframe(df_filtered.reset_index(drop=True), width='stretch')
# with tab2:
#     st.dataframe(df, width='stretch')
# 
# st.caption("Usa los filtros de la izquierda para explorar los datos por año, departamento o periodo académico.")
# 
# # 💬 Interacción de ejemplo (código adicional que solicitaste)
# st.subheader("💬 Interacción de ejemplo")
# user_input = st.text_input("Escribe algo aquí:", "Hola Streamlit!")
# st.write(f"Has escrito: {user_input}")